/** Operational Ledger design reminder: source lists are seeded from the attached AP27 Key sheet, never fabricated planning data. */
import type { ActivityType, Brand } from "./models";

const id = (prefix: string, value: string) => `${prefix}-${value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;

export const DATA_HEADERS = [
  "Serial", "Brand", "Team", "Activity", "Description", "Country", "Specialty", "Date", "Location",
  "Number (Units / Customers)", "Cost / Item", "Total Cost", "Steps", "Responsibility", "Ownership",
  "Timeline", "Status", "Quarter", "P.Manager", "Payment Time Line",
] as const;

const activityNames = [
  "Group Meeting", "Group Presentation", "Offline Lecture", "Round Table Discussion", "HCP Sponsorship", "Medical Gift",
  "Brand Reminder", "Online lecture", "Public Awareness", "Design & Concept", "Printed Materials", "International Standalone Meeting",
  "Launch symposium", "Consultation", "Online subscription", "Enlisting fees", "CME Registration", "Local Conference Sponsorship",
  "Cycle Meeting", "Medical / Marketing Training", "Commercial Support", "Local Standalone Meeting", "International Conference Sponsorship",
  "Advisory Board", "Focus Group",
];

const brandNames = [
  "Ambolar",
  "Antiplex",
  "Aresil",
  "Ciprodar - Qurex",
  "Clavodar",
  "Dad Teething Gel",
  "Daroxime",
  "Diapride - Glumine",
  "Diapride -M",
  "Diclofast-Solvast",
  "Doxydar",
  "Famodar",
  "Fastikol",
  "Flucoheal",
  "Gamcet",
  "Hairgrow",
  "Lipodar",
  "Locan",
  "Lovista - Evadad",
  "Mycoheal",
  "Myogesic",
  "Omedar",
  "Ophtamesone",
  "Tyra 5",
  "Xenpa - met",
  "Xenpa",
  "Zarlan - Xivar",
  "Amlodar - Amolar",
  "Amoxydar - Moxidad",
  "Cibramine",
  "Domperide",
  "Esperal-Espedar-Tiaqueen",
  "Gizlan",
  "Gizlan Plus",
  "Liblab-Rectolab-Avilop",
  "Mirale",
  "Mozart - HCT",
  "Mozart",
  "Olzan",
  "Cloracef",
  "Vitadad - DivaD",
  "Diclogesic",
  "Cephadar",
  "Clomifert - Avaklamin",
  "Pantodar",
  "Matador - Livador",
  "Mixif - Murex",
  "Proctoheal-Proctodar",
  "Risdone - Razvan",
  "Rozitta - Robust",
  "Volar",
  "Loratan - Loradad",
  "Carbatol",
  "Dilzacard",
  "Formit - Gliafor",
  "Glunorm",
  "Glunorm M",
  "Pedexa",
  "Azord - Xevaneer",
  "Claridar",
  "Gizlan Duo - Gizamlo",
  "Promivol",
  "Tamolin",
  "Vitadad - DivaD C & Z",
  "Histafen-Histaderm Topical",
  "Ibugesic",
  "Ophtamolol",
  "Ceclor",
  "Keflex",
  "Anxetin",
  "Aphrodil",
  "Artrol",
  "Cadila",
  "Cimedine",
  "Combizart",
  "Combizart HCT",
  "Erythrodar",
  "Glenpa",
  "Glisenz",
  "Isocard",
  "Lincodar",
  "Miloxam-Miloxydar-Anticox",
  "Nesma",
  "Ophtazolin",
  "Oprim",
  "Rectolyn",
  "Rina",
  "Rozandia",
  "Smooderm",
  "Vilapro",
  "Violet",
  "Pamol",
  "Angiosar - Plus",
  "Broncholar",
  "DAD Care",
  "DAD Ice",
  "Epigab",
  "Indogesic",
  "Ketodar",
  "Lima",
  "Lisocard",
  "Momizal",
  "Montana",
  "Motrinex",
  "Nerva Foot Care",
  "Olive Leaf Extract",
  "Opal",
  "Rina D-Rina Extra",
  "Trimidar M",
  "Tyra",
  "Vilasar",
  "Vilasar-Plus",
  "Angiosar",
  "Daromed T",
  "Neobacin",
  "Pectolyn",
  "Roxamed",
  "Pelco-M",
  "Amuretic",
  "RM - PM",
  "Sucrazide",
  "Dadcrome",
  "Atrenova",
  "Capocard",
  "Rozalip",
  "Dasatinib",
  "Flobex",
  "Deplazen",
  "Deplazen - Met",
  "Nulina-M",
  "Pekab",
  "Setaglib Met",
].sort((left, right) => left.localeCompare(right));

export const initialActivityTypes: ActivityType[] = activityNames.map((name) => ({ id: id("activity", name), name }));
export const initialBrands: Brand[] = brandNames.map((name) => ({ id: id("brand", name), name }));

export const makeId = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
export const now = () => new Date().toISOString();
export const quarterFor = (date: string) => date ? `Q${Math.floor(new Date(`${date}T12:00:00`).getMonth() / 3) + 1}` : "";
